#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get -y install nginx
sudo chown -R "$USER" /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
