#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get -y install nginx
sudo chown -R "$USER" /var/www/
sudo chown -R "$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
