#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 3681-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 4254-web-01 34.201.146.170:80 check\n\tserver 4254-web-02 54.86.254.146:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
