#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.0.\* -y
sudo sed -i "$ a frontend http_web\n\tbind *:80\n\tmode http\n\tdefault_backend my_backend\n" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a backend my_backend\n\tbalance roundrobin\n\tserver 4254-web-01 34.201.146.170:80 check\n\tserver 4254-web-02 54.86.254.146:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
