#!/usr/bin/env bash
# run ngnix as nginx listening on all active IPs on port 8080 
pkill apache
chown -R nginx:nginx /etc/nginx
chmod +r /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default 
su -c nginx nginx
